name: Pull Request

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
    - name: Build and test
      run: xcodebuild clean build test -project ProjexSync/ProjexSync.xcodeproj -scheme "ProjexSync" -destination "platform=iOS Simulator,OS=16.4,name=iPhone 14 Pro" ONLY_ACTIVE_ARCH=YES
